---
parser: "@typescript-eslint/parser"
extends:
  - plugin:@typescript-eslint/recommended
ignorePatterns: [ "*.js" ]
rules:
  '@typescript-eslint/no-explicit-any': [ off ]
  '@typescript-eslint/explicit-module-boundary-types': [ off ]
