---
include:
  - local: .gitlab-ci.deploy.yml

# @Description Install npm packages
npm-install:
  stage: .pre
  image: node
  artifacts:
    paths:
      - node_modules/
  script:
    - npm install --no-audit

.test-parent-job:
  stage: test
  image: node
  allow_failure: true

# @Description Find security vulnerabilities in node_modules
npm-audit:
  extends: .test-parent-job
  needs: [ ]
  allow_failure: true
  script: npm audit

# @Description Find outdated packages in node_modules
npm-outdated:
  extends: [ .test-parent-job ]
  needs: [ npm-install ]
  script:
    - npx -s ncu -e2 --deprecated
