---
name: build
on: push
jobs:

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run ESLint
        run: npm --silent run lint

  typescript-compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run Typescipt Compiler
        run: npm --silent run build

  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Generate SSH key
        run: cat /dev/zero | ssh-keygen -q -N ""
      - name: Git ignore host key verification
        run: export GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
      - name: Run tests
        run: npm --silent run test
